### PR TITLE
antivirus: defender update and active status

### PR DESCRIPTION
**Pull request by sajjadhossanshimanto**
added antivirus active status and defender update status determine for wmi "SecurityCenter" query products

### CODE REVIEW

**Comment by sajjadhossanshimanto** [comment]
windows_tools.antivirus.get_installed_antivirus_software()# now vs then
now:[
    {'Definition Status': 'Unknown',
    'Real-time Protection': 'Unknown',
    'name': 'Windows Defender'
    },
    {'Definition Status': 'Up to date',
    'Real-time Protection': 'Enabled',
    'name': 'Avast Antivirus'
    },
    {'name': 'Avast Premium Security',
    'publisher': 'Avast Software',
    'version': '21.4.2464'
    }
]

then:[
    {'name': 'Windows Defender'
    },
    {'name': 'Avast Antivirus'
    },
    {'name': 'Avast Premium Security',
     'publisher': 'Avast Software',
     'version': '21.4.2464'
    }
]

**Review by deajan — CHANGES_REQUESTED** [review]
By adding `antivirus_state` dict, you reinvent the purpose of the `securitycenter_get_product_*()` functions which are more detailled.
Please use those functions to construct your result instead of a static dict.

**Comment by sajjadhossanshimanto** [comment]
Sir,
In order to use `securitycenter_get_product_*()` functions we need the status code. But `get_installed_antivirus_software` function is not producing the status code

**Comment by deajan** [comment]
The WMI call windows_tools.wmi_queries.query_wmi('SELECT * FROM AntivirusProduct', namespace='SecurityCenter') gives the state.
Instead of using your predefined `antivirus_state` dict, you must use the `securitycenter_get_product_*()` functions to decode the state, because it's more versatile, and is not redundant.

**Comment by sajjadhossanshimanto** [comment]
yes sir,
I should use `securitycenter_get_product_*()` functions but 

- how a normal user _( those who useally doesn't inspect through downloaded modules )_ would know **"what query string is to use and how"** !!
- also in terms of performance is it not obvious to repeat the same task

**Comment by deajan** [comment]
Sorry, but I think you misunderstood the way this works.
I have added what you are seeking in commit https://github.com/netinvent/windows_tools/commit/634d0f26c698cd5d3bb072e682332f8122128665 but with boolean results instead of strings.
Also, there is no need to know any query string nor repeat any operation.

Best regards.

**Pull request closed without merging**
